---
- name: Update host
  hosts: zabbixserver
  remote_user: root
  become: true

  tasks:
    - name: Ping host
      ansible.builtin.ping:

    - name: Make sure xz-utils is installed
      ansible.builtin.apt:
        name: xz-utils
        state: present

    - name: Install Zabbix parent
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu24.04_all.deb

    - name: Install Zabbix packages
      ansible.builtin.apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.3-pgsql
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent
        update_cache: true

    - name: Install postgresql
      ansible.builtin.apt:
        name: postgresql
        state: present

    - name: Install psycopg2
      ansible.builtin.apt:
        name: python3-psycopg2
        state: present

    - name: Install ACL
      ansible.builtin.apt:
        name: acl
        state: present

    - name: Create user for Zabbix in postgresql
      community.postgresql.postgresql_user:
        name: zabbix
        password: "{{ lookup('ansible.builtin.env', 'TF_VAR_zabbixdbpassword', Default=Undefined) }}"
        login_host: 127.0.0.1
      become_user: postgres

    - name: Create DB for Zabbix
      community.postgresql.postgresql_db:
        name: zabbix
        owner: zabbix
        login_host: 127.0.0.1
      become_user: postgres

    - name: Import DB schema and initial data
      community.postgresql.postgresql_db:
        name: zabbix
        target: /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz
        login_host: 127.0.0.1
      become_user: postgres

    #- name: Replace a localhost entry searching for a literal string to avoid escaping
    #  ansible.builtin.lineinfile:
    #    path: /etc/hosts
    #    search_string: 'DBPassword='
    #    line: 127.0.0.1 localhost
    #    owner: root
    #    group: root
    #    mode: '0644'