---
- name: Update host
  hosts: zabbixserver
  remote_user: root
  become: true

  tasks:
    - name: Ping host
      ansible.builtin.ping:

    - name: Make sure xz-utils is installed
      ansible.builtin.apt:
        name: xz-utils
        state: present

    - name: Install Zabbix parent
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu24.04_all.deb

    - name: Install Zabbix packages
      ansible.builtin.apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.3-pgsql
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent
        update_cache: true

    - name: Install postgresql
      ansible.builtin.apt:
        name: postgresql
        state: present

    - name: Install psycopg2
      ansible.builtin.apt:
        name: python3-psycopg2
        state: present

    - name: Install ACL
      ansible.builtin.apt:
        name: acl
        state: present

    - name: Set postgres user password
      ansible.builtin.command: sudo -u postgres psql -c "ALTER USER postgres PASSWORD '{{ lookup('ansible.builtin.env', 'TF_VAR_postgrespassword', Default=Undefined) }}';"

    - name: Create user for Zabbix in postgresql
      community.postgresql.postgresql_user:
        name: zabbix
        password: "{{ lookup('ansible.builtin.env', 'TF_VAR_zabbixdbpassword', Default=Undefined) }}"
        login_host: localhost
        login_password: "{{ lookup('ansible.builtin.env', 'TF_VAR_postgrespassword', Default=Undefined) }}"

    - name: Create DB for Zabbix
      community.postgresql.postgresql_db:
        name: zabbix
        owner: "zabbix"
        login_host: 127.0.0.1
        login_password: "{{ lookup('ansible.builtin.env', 'TF_VAR_postgrespassword', Default=Undefined) }}"

    - name: Import DB schema
      community.postgresql.postgresql_db:
        state: restore
        name: zabbix
        target: /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz
        login_host: 127.0.0.1
        login_user: zabbix
        login_password: "{{ lookup('ansible.builtin.env', 'TF_VAR_zabbixdbpassword', Default=Undefined) }}"

    - name: Add DB password to zabbix configuration
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        search_string: '# DBPassword='
        line: "DBPassword={{ lookup('ansible.builtin.env', 'TF_VAR_zabbixdbpassword', Default=Undefined) }}"

    - name: Make nginx 8080 defaultserver
      ansible.builtin.lineinfile:
        path: /etc/zabbix/nginx.conf
        search_string: "listen"
        line: "listen 8080 default_server;"

    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Restart zabbix-server.service
      ansible.builtin.systemd_service:
        name: zabbix-server
        state: restarted
        enabled: true

    - name: Restart zabbix-agent.service
      ansible.builtin.systemd_service:
        name: zabbix-agent
        state: restarted
        enabled: true

    - name: Restart nginx.service
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: true

    - name: Restart php8.3-fpm.service
      ansible.builtin.systemd_service:
        name: php8.3-fpm
        state: restarted
        enabled: true
